Repository INM-6/viziphant, pull requests merged in 2023-11, with the labels that each got.

#71 [Doc] readthedocs: configuration key build.image is deprecated, changed to build.os
  .readthedocs.yaml
Labels: documentation

#72 [Fix] remove .join in plot_ue function
  viziphant/unitary_event_analysis.py
Labels: bug

#75 Add code for hypergraph visualizations of pattern techniques
  requirements/requirements.txt
  viziphant/patterns.py
  viziphant/patterns_src/__init__.py
  viziphant/patterns_src/hypergraph.py
  viziphant/patterns_src/view.py
Labels: enhancement
